# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-perspectives"
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Asher Van Brunt"]
  s.date = "2011-11-22"
  s.description = "Presenters for DataMapper models."
  s.email = "asher.vanbrunt@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/dm-perspectives.rb",
    "lib/dm-perspectives/base.rb",
    "test/data.rb",
    "test/helper.rb",
    "test/test_dm-perspectives.rb"
  ]
  s.homepage = "http://github.com/okbreathe/dm-perspectives"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Presenters for DataMapper models."
  s.test_files = [
    "test/data.rb",
    "test/helper.rb",
    "test/test_dm-perspectives.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tzinfo>, [">= 0.3.23"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_runtime_dependency(%q<dm-sqlite-adapter>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-migrations>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-types>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-core>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-do-adapter>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<dm-active_model>, [">= 1.0.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<dm-core>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
    else
      s.add_dependency(%q<tzinfo>, [">= 0.3.23"])
      s.add_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 1.0.2"])
      s.add_dependency(%q<dm-migrations>, [">= 1.0.2"])
      s.add_dependency(%q<dm-types>, [">= 1.0.2"])
      s.add_dependency(%q<dm-validations>, [">= 1.0.2"])
      s.add_dependency(%q<dm-core>, [">= 1.0.2"])
      s.add_dependency(%q<dm-do-adapter>, [">= 1.0.2"])
      s.add_dependency(%q<dm-active_model>, [">= 1.0.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<dm-core>, [">= 1.0.0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    end
  else
    s.add_dependency(%q<tzinfo>, [">= 0.3.23"])
    s.add_dependency(%q<activesupport>, [">= 3.0.3"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 1.0.2"])
    s.add_dependency(%q<dm-migrations>, [">= 1.0.2"])
    s.add_dependency(%q<dm-types>, [">= 1.0.2"])
    s.add_dependency(%q<dm-validations>, [">= 1.0.2"])
    s.add_dependency(%q<dm-core>, [">= 1.0.2"])
    s.add_dependency(%q<dm-do-adapter>, [">= 1.0.2"])
    s.add_dependency(%q<dm-active_model>, [">= 1.0.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<dm-core>, [">= 1.0.0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
  end
end

